name: Github actions demo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      SOLUTION: src/TestGithubActions/TestGithubActions.sln

    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore $SOLUTION
      - name: Build
        run: dotnet build $SOLUTION --configuration Release --no-restore
      - name: Test
        run: dotnet test $SOLUTION --no-restore --verbosity normal